spring.application.name=fondos-api
server.port=${SERVER_PORT:8081}
server.servlet.context-path=/app
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://admin:admin123@localhost:27017/testdb?authSource=admin}
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:pizzaappnoreply@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:twgqqerirwonrtlo}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
notification.email.from=pizzaappnoreply@gmail.com
notification.sms.account-sid=ACxxxx
notification.sms.auth-token=xxxx
notification.sms.from-number=+14155238886

